spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: lucius
    password: yoksetioxD
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect