spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/chicken
    username: root
    password: fmiguel01
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect